### ISSUE TITLE
the name 'Database Error' is defined in the libraries 'firebase_database.dart' and 'geofire.dart'

### ISSUE THREAD

**Issue by ColquePaxi** [bramvbilsen/Flutter-GeoFire#1]
Hello BramVbilsen,
Very very cool your plugin. Thank you, man!!!!
After updated my firebase_database.dart (from 0.0.12 to 0.3.0) the geofire no works fine.
Is there any solution to apply in this case?

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.1.1                                             # new
  google_sign_in: 0.3.1                                           # new
  firebase_analytics: 0.0.4                                       # new
  firebase_auth: 0.2.0                                            # new
  #firebase_database: 0.0.12                                       # new
  firebase_database: "^0.1.0"                                       # new
  firebase_storage: 0.0.5                                         # new
  intl: 0.15.2
  numberpicker: "^0.1.0"
  geocoder: "^0.0.1"                                              # Busca de endereço via API Google Maps

  # Para usar o runTransaction e fazer um contador no Firebase
  firebase_core: "0.0.7"                                         # new
  cupertino_icons: ^0.1.0

  geofire:
    git:
      url: "git://github.com/bramvbilsen/Flutter-GeoFire.git"
```
